---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: workload
aggregationRule:
  clusterRoleSelectors:
  - matchLabels:
      platform.kadras.io/aggregate-to-workload: "true"
rules: []
