apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  creationTimestamp: null
  name: kadras-rbac.packages.kadras.io.0.0.0
spec:
  licenses:
  - Apache 2.0
  refName: kadras-rbac.packages.kadras.io
  releaseNotes: https://github.com/kadras-io/kadras-rbac/releases
  releasedAt: null
  template:
    spec:
      deploy:
      - kapp: {}
      fetch:
      - git: {}
      template:
      - ytt:
          paths:
          - config
      - kbld: {}
  valuesSchema:
    openAPIv3: {}
  version: 0.0.0

---
apiVersion: data.packaging.carvel.dev/v1alpha1
kind: PackageMetadata
metadata:
  creationTimestamp: null
  name: kadras-rbac.packages.kadras.io
spec:
  categories:
  - rbac
  displayName: kadras-rbac
  longDescription: Default roles and RBAC configuration for the Kadras Engineering
    Platform, supporting users and service accounts.
  maintainers:
  - name: Thomas Vitale
  providerName: Kadras
  shortDescription: Default roles and RBAC configuration for the Kadras Engineering
    Platform.
  supportDescription: Go to https://kadras.io for documentation and https://github.com/kadras-io/kadras-rbac
    for community support.

---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  annotations:
    kctrl.carvel.dev/local-fetch-0: .
  creationTimestamp: null
  name: kadras-rbac
spec:
  packageRef:
    refName: kadras-rbac.packages.kadras.io
    versionSelection:
      constraints: 0.0.0
  serviceAccountName: kadras-install-sa
status:
  conditions: null
  friendlyDescription: ""
  observedGeneration: 0
